export const GET_POCKET_TOKEN_START = "GET_POCKET_TOKEN_START";
export const GET_POCKET_TOKEN_SUCCESS = "GET_POCKET_TOKEN_SUCCESS";
export const GET_POCKET_TOKEN_FAIL = "GET_POCKET_TOKEN_FAIL";
export const GET_POCKET_TOKEN_COMPLETE = "GET_POCKET_TOKEN_COMPLETE";

export const UPDATE_STATS_START = "UPDATE_STATS_START";
export const UPDATE_STATS_SUCCESS = "UDPATE_STATS_SUCCESS";
export const UPDATE_STATS_FAILED = "UPDATE_STATS_FAILED";
